# The Publication Field
crossref_first_mapping = {'first_score': 'score',
                          'first_title': 'title',
                          'first_normalized_score': 'normalizedScore',
                          'first_full_citation': 'fullCitation',
                          'first_doi': 'doi'}

crossref_second_mapping = {'second_score': 'score',
                           'second_title': 'title',
                           'second_normalized_score': 'normalizedScore',
                           'second_full_citation': 'fullCitation',
                           'second_doi': 'doi'}

doi_mapping = dict.fromkeys(['AU', 'DA', 'DO', 'IS', 'PB', 'SN', 'SP', 'T2', 'TI', 'TY', 'VL'])

scopus_mapping = {'s_url': 'prism:url',
                  's_id': 'dc:identifier',
                  's_eid': 'eid',
                  's_article_title': 'dc:title',
                  's_first_author': 'dc:creator',
                  's_journal_name': 'prism:publicationName',
                  's_journal_issn': 'prism:issn',
                  's_journal_isbn': 'prism:isbn',
                  's_journal_eIssn': 'prism:eIssn',
                  's_journal_volume': 'prism:volume',
                  's_journal_issueIdentifier': 'prism:issueIdentifier',
                  's_journal_pageRange': 'prism:pageRange',
                  's_journal_coverDate': 'prism:coverDate',
                  's_journal_coverDisplayDate': 'prism:coverDisplayDate',
                  's_journal_type': 'prism:aggregationType',
                  's_publication_item_identifier': 'pii',
                  's_pubmed_id': 'pubmed-id',
                  's_orcid': 'orcid',
                  's_doi': 'prism:doi',
                  's_description': 'dc:description',
                  's_citedby_count': 'citedby-count',
                  's_authkeywords': 'authkeywords',
                  's_source_id': 'source-id',
                  's_article_number': 'article-number'}

journal_mapping = {'j_1ST_YR_PUB': '1ST_YR_PUB',
                   'j_5YR_IF_DENOMINATOR': '5YR_IF_DENOMINATOR',
                   'j_5YR_IF_NUMERATOR': '5YR_IF_NUMERATOR',
                   'j_5YR_IMPACT_FACTOR': '5YR_IMPACT_FACTOR',
                   'j_ARTL_INFLUENCE': 'ARTL_INFLUENCE',
                   'j_CATEGORY_CODE': 'CATEGORY_CODE',
                   'j_CATEGORY_DESCRIPTION': 'CATEGORY_DESCRIPTION',
                   'j_CATEGORY_RANKING': 'CATEGORY_RANKING',
                   'j_CITED_HALF_LIFE': 'CITED_HALF_LIFE',
                   'j_COUNTRY': 'COUNTRY',
                   'j_EIGENFACTOR': 'EIGENFACTOR',
                   'j_IF_DENOMINATOR': 'IF_DENOMINATOR',
                   'j_IF_NUMERATOR': 'IF_NUMERATOR',
                   'j_IMMEDIACY_INDEX': 'IMMEDIACY_INDEX',
                   'j_IMPACT_FACTOR': 'IMPACT_FACTOR',
                   'j_ISO_ABBREV': 'ISO_ABBREV',
                   'j_ISSN': 'ISSN',
                   'j_ITEMS_JCR_YR3': 'ITEMS_JCR_YR3',
                   'j_ITEMS_JCR_YR4': 'ITEMS_JCR_YR4',
                   'j_ITEMS_JCR_YR5': 'ITEMS_JCR_YR5',
                   'j_JIF_PERCENTILE': 'JIF_PERCENTILE',
                   'j_LANGUAGE': 'LANGUAGE',
                   'j_NORMEIGENFACTOR': 'NORMEIGENFACTOR',
                   'j_QUARTILE_RANK': 'QUARTILE_RANK',
                   'j_TITLE': 'TITLE',
                   'j_Title20': 'Title20',
                   'j_categories': 'categories'}

author_mapping = {'a_cited_by_count': 'coredata+cited-by-count',
                  'a_citation_count': 'coredata+citation-count',
                  'a_h_index': 'h-index',
                  'a_coauthor_count': 'coauthor-count'}

# The Grant Field
grant_mapping = {'NIH': r'National Institutes of Health|NIH',
                 'NSF': r'National Science Foundation|NSF',
                 'USDA': r'US Department of Agriculture|USDA',
                 'NEH': r'National Endowment for the Humanities|NEH',
                 'NEA': r'National Endowment for the Arts|NEA',
                 'IES': r'Institute of Education Sciences|IES',
                 'CEC': r'California Energy Commission',
                 'CDE': r'California Department of Education',
                 'CDFA': r'California Department of Food and Agriculture',
                 'RAF': r'Rita Allen Foundation',
                 'DLPF': r'The David & Lucile Packard Foundation',
                 'WMFK': r'W.M. Keck Foundation',
                 'NCI': r'National Cancer Institute|NCI',
                 'NEI': r'National Eye Institute|NEI',
                 'NHLBI': r'National Heart[,]? Lung[,]? and Blood Institute|NHLBI',
                 'NHGRI': r'National Human Genome Research Institute|NGHRI',
                 'NIA': r'National Institute on Aging|NIA',
                 'NIAAA': r'National Institute on Alcohol Abuse and Alcoholism|NIAAA',
                 'NIAID': r'National Institute of Allergy and Infectious Diseases|NIAID',
                 'NIAMS': r'National Institute of Arthritis and Musculoskeletal and Skin Diseases|NIAMS',
                 'NIBIB': r'National Institute of Biomedical Imaging and Bioengineering|NIBIB',
                 'NICHD': r'National Institute of Child Health and Human Development|NICHD',
                 'NIDCD': r'National Institute on Deafness and Other Communication Disorders|NIDCD',
                 'NIDCR': r'National Institute of Dental and Craniofacial Research|NIDCR',
                 'NIDDK': r'National Institute of Diabetes and Digestive and Kidney Diseases|NIDDK',
                 'NIDA': r'National Institute on Drug Abuse|NIDA',
                 'NIEHS': r'National Institute of Environmental Health Sciences|NIEHS',
                 'NIGMS': r'National Institute of General Medical Sciences|NIGMS',
                 'NIMH': r'National Institute of Mental Health|NIMH',
                 'NIMHD': r'National Institute on Minority Health and Health Disparities|NIMHD',
                 'NINDS': r'National Institute of Neurological Disorders and Stroke|NINDS',
                 'NINR': r'National Institute of Nursing Research|NINR',
                 'NLM': r'National Library of Medicine|NLM',
                 'USAID': r'US Agency for International Development|USAID',
                 'DOS': r'US Department of State|DOS',
                 'DOD': r'US Department of Defense|DOD',
                 'HHS': r'US Department of Health and Human Services|HHS'}
